
GET http://localhost:3000/todos/

###

GET http://localhost:3000/todos/:todoId/

###

POST http://localhost:3000/todos/

###

PUT http://localhost:3000/todos/:todoId/

###
DELETE http://localhost:3000/todos/:todoId/